//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int Id { get; set; }
        public Nullable<int> Bill_Id { get; set; }
        public Nullable<int> ProId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Bill_Price { get; set; }
        public string Bill_Money { get; set; }
    
        public virtual BillCustomer BillCustomer { get; set; }
        public virtual Product Product { get; set; }
    }
}
