//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillCustomer()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public int Bill_Id { get; set; }
        public string TotalMoney { get; set; }
        public Nullable<System.DateTime> DateBuy { get; set; }
        public Nullable<System.DateTime> DatePay { get; set; }
        public string Request { get; set; }
        public string TypePay { get; set; }
        public Nullable<int> Status { get; set; }
        public string CustomId { get; set; }
        public string UserId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User_ User_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
    }
}
