//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visistor
    {
        public int Id { get; set; }
        public Nullable<int> UserOnline { get; set; }
        public Nullable<long> iVisistor { get; set; }
        public Nullable<int> iVisistorOnlineDate { get; set; }
        public Nullable<System.DateTime> DateOnline { get; set; }
    }
}
